version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    command: ['--default-authentication-plugin=mysql_native_password']

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"