version: '3'

services:
  app:
    build: .
    ports:
      - "1215:1215"
    depends_on:
      - mysql
      - redis
    environment:
      - FLASK_ENV=development

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    command: ['--default-authentication-plugin=mysql_native_password']

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"